apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-service
  namespace: honeypot
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
  selector:
    app: minecraft-server