apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 9200
    nodePort: 30000
    targetPort: 9200
    protocol: TCP
  selector:
    app: elasticsearch
