apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"pf-pot-service","namespace":"honeypot"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":8000}],"selector":{"app":"pf-pot"},"type":"LoadBalancer"}}
    metallb.universe.tf/ip-allocated-from-pool: honeypot-pool
  creationTimestamp: "2024-10-03T03:04:49Z"
  name: pf-pot-service
  namespace: honeypot
  resourceVersion: "2338022"
  uid: ddab6667-6fd8-4f66-92a7-36b0f803ac8d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.187.177
  clusterIPs:
  - 10.104.187.177
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30200
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: pf-pot
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.10.11
      ipMode: VIP
