apiVersion: v1
kind: Service
metadata:
  name: mmysql-service
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql-server
