apiVersion: v1
kind: Service
metadata:
  name: cowrie
  namespace: honeypot
spec:
  type: NodePort
  ports:
  - port: 2222
    targetPort: 2222
    protocol: TCP
  selector:
    app: cowrie
---
apiVersion: v1
kind: Service
metadata:
  name: cowrie-ssh-server
  namespace: honeypot
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: cowrie
