apiVersion: v1
kind: Service
metadata:
  name: geolite-api-service
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: geolite-api