apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: honeypot
data:
  filebeat.yml: |
    filebeat.inputs:
    # Input for Cowrie Logs
    - type: log
      enabled: true
      paths:
        - /var/log/cowrie.log
      tags: ["cowrie"]

    # Input for PFPot Logs
    - type: log
      enabled: true
      paths:
        - /var/log/log.txt
      tags: ["pfpot"]

    output.logstash:
      hosts: ["logstash.monitoring.svc.cluster.local:5044"]
