apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: honeypot
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.txt
        - /var/log/*.log

    output.logstash:
      hosts: ["logstash.monitoring.svc.cluster.local:5044"] 

  


    