apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: honeypot
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/log.txt
        - /var/log/cowrie.log
      fields_under_root: true


    output.logstash:
      fields_under_root:
          - source: ${path}
      hosts: ["logstash.monitoring.svc.cluster.local:5044"] 

  


    