apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: elk-pv
  namespace: monitoring
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /persistent-volumes/elk