apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: prometheus-alert-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /persistent-volumes/prometheus-alert