apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    nodeSelector:
        role: master
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.5.0 # Use the appropriate version
        ports:
        - containerPort: 5044 # Default port for beats input
        env:
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch:9200" # Adjust this if necessary
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-pipeline-config