apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        role: master
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.5.0 # Use the appropriate version
        volumeMounts:
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        ports:
        - containerPort: 5044 # Default port for beats input
        - containerPort: 9600
        env:
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch:9200" # Adjust this if necessary
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: logstash-pipeline
        configMap:
          name: logstash-config