apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config
data:
  pipeline.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}"]
      }
    }