apiVersion: v1
kind: Service
metadata:
  name: pf-pot-service
  namespace: honeypot
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: pf-pot