apiVersion: v1
kind: Service
metadata:
  name: packet-analysis-tool-service
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: packet-analysis-tool