apiVersion: apps/v1
kind: Deployment
metadata:
  name: packet-sniffer
  namespace: honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packet-sniffer
  template:
    metadata:
      labels:
        app: packet-sniffer
    spec:
      nodeSelector:
        role: worker
      hostNetwork: true  # Use the host network namespace
      containers:
        - name: tcpdump-socat
          image: cjbates02/tcpdump-socat:latest
          ports:
          - containerPort: 6565
          command: ["sh", "-c", "tcpdump -i eno1 -U -w - | socat - TCP-LISTEN:6565,fork"]
          resources:
            limits:
              cpu: "100m"  # Limit CPU usage
              memory: "128Mi"  # Limit memory usage
