apiVersion: apps/v1
kind: Deployment
metadata:
  name: packet-sniffer
  namespace: honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packet-sniffer
  template:
    metadata:
      labels:
        app: packet-sniffer
    spec:
      nodeSelector:
        role: worker
      hostNetwork: true
      containers:
        - name: tcpdump-socat
          image: cjbates02/tcpdump-socat:latest
          ports:
          - containerPort: 6565
          command: ["sh", "-c", "tcpdump -n -i eno1 -U -B 8192 -w - | socat - TCP-LISTEN:6565,fork"]
          securityContext:
            privileged: true
          # command: ["sh", "-c", "tcpdump -n -i any -l"]
          resources:
            limits:
              cpu: "500m"  # Limit CPU usage
              memory: "512Mi"  # Limit memory usage
