apiVersion: v1
kind: Service
metadata:
  name: packet-sniffer
  namespace: honeypot
spec:
  selector:
    app: tcpdump-socat
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer